### ISSUE TITLE
Game server?

### ISSUE THREAD

**Issue by bbqbaron** [jhmullen/feast-react#12]
Depending on how the app is currently deployed, perhaps we should add a node server? Can be run however Jimmy likes; we could try out the hotness that is [Nextjs] (example with sockets [here](https://github.com/sergiodxa/next-socket.io)). I've never used it but it's designed to run isomorphic React apps and is super popular; could be a good learning opportunity.

**Comment by jhmullen** [comment]
I agree that we should add a node server, the node ecosystem and relative simplicity of socket.io was part of the reasoning behind the selection of React in the first place.  

I am not familiar with Nextjs, nor isomorphic React in general.  As far as I understand, the project as is is entirely client-side.  Will it require any major rewrites of the codebase?  The linked example seems simple enough.

Perhaps more importantly, how does this affect remote deployment?  I assume server-side react requires server-side configs (right now I just drop the transformed.js into an htdocs dir).

**Comment by bbqbaron** [comment]
Ideally we can leave our existing code as-is; Next is supposed to work nicely with React while providing the ability to have a server around it. I don't mind going through the docs to save you the effort; if it's a giant pain we can just do something else.

Deployment! It just so happens that Next is by Zeit, which provides a Node deployment CLI called [Now](https://zeit.co/now). Similar answer to Next; if it's not easy we can just roll our own ECS or Beanstalk instance or something. Hopefully Next and Now

**Comment by jhmullen** [comment]
Cool man - I'd love for you to run with it!  The netcode side of this was always the more intimidating for me.  Let me know if there's anything special I need to do to get set up.  Now seems very cool.

**Comment by jhmullen** [comment]
Adding to that, It was always my hope to get the multiplayer done early (way before rules and even mana counting).  It sits alongside "visual UX improvements" and "bare minimum of moving cards between zones" as my major priorities.   The sooner we can get this in front of John et al., even in its jankier form, the sooner we will be cutting and adding cards that obviously work / don't work.

**Comment by bbqbaron** [comment]
I got an example with sockets running on Now; the major blocker is that Next doesn't automatically work with the precise way we're doing CSS (importing files as modules with `style-loader`/`css-loader`). I fiddled a bit; the best supported alternative is to use `styled-jsx`, which I think would end up looking a bit like the below. I find CSS in template strings a bit peculiar; I'd prefer either CSS as code/data or `.css` files, but I'm also not very conversant in styling and am willing to take other people's word for it.

If this doesn't taste very good, there are many many other options. The one we're using at work is Typescript and has many, many other needs, so is wild overkill; I'd have to research other options. Thoughts?

Example: (yes, you have to include styles as an element in the DOM)
```
// AppStyle.js or however we want to organize it
export default <style jsx>{`
  .root {
    blah blah
  }
`}</style>

// App.js
import style from './AppStyle'

export const App = () => <div>
  {style}
</div>
```

**Comment by jhmullen** [comment]
Wuf, I agree on not tasting good.  

I wouldn't mind the strange syntax of all of this, but the template strings give me the heebie-jeebies.  I too prefer my CSS as `.css` philosophically, but on a technical level, I'm more concerned about losing syntax highlighting.  I noticed in their readme that only a few text editors support syntax highlighting for templated stylejsx.

I agree that Typescript would be overkill for this.  I'd be interested to learn if there are other non-overkill options that allow us to keep regular CSS files

**Comment by jhmullen** [comment]
That said: If finding an alternative ends up being a pain, I'm willing to sack CSS purity for ease of networking.  I'm already a blind cave worm when it comes to CSS so I shouldn't die on the syntax hill.

**Comment by bbqbaron** [comment]
Delivered in #15
