### ISSUE TITLE
Design principles and short-term goals?

### ISSUE THREAD

**Issue by jhmullen** [jhmullen/feast-react#14]
What is a good place for general project direction to live?

I didn't want to hijack the thread on nextjs/sockets for this, but I did want to clarify the short-term goals of this project.

The main goal is an MVP to test remotely whether this game is even fun.  As such, the most important first goals are:

- network play for remote testing
- naive drag & drop state changes for hand, party, etc.
- deck management, "move a card from one zone to another" actions, as well as utilities for shuffling, discarding, or graveyard/deck search.
- convenience methods for highest level actions (draw a hand, end a turn and move guests, etc)

Because John's card design is so wacky and full of exceptions, we could spend forever trying to chase down and hard code how prestige is calculated, when someone can or can't join a party, and so on.  For this first pass, I'm content to let a great deal of the calculation fall to a yellow legal pad and the honor system.  If abilities become solid and great, we can then start to hard code them.

Would the wiki be a good place for these kinds of goals?

**Comment by bbqbaron** [comment]
Oh, point taken; I hadn't thought of it as a low-level card simulator, but that actually makes perfect sense. It may be enough for me merely to be chastised and bear this goal in mind 😄

**Comment by jhmullen** [comment]
No chastising intended!  Your help is amazing and appreciated :)  Mostly just trying to sync up.  If the game does end up being fun I would love to continue on coding more advanced stuff and rules that lessen the need to keep track ourselves.
